version: '3.4'
services:
    sut:
        container_name: power_test
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: test
        image: is_power:unit-test
        command: tox
